"""
Django settings for VirtualMedicalCoder project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


REST_FRAMEWORK = {
    # Allow both cookie-based custom auth and SimpleJWT token auth.
    # Per-view permission overrides (AllowAny) are still supported.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.JWTCookieAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}

# SECURITY: load sensitive values from environment variables when available
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-q6^bvh)^6f-$0q^scnomny%0i(e+!6mi+-vopi8l96a#s69e@&")

# DEBUG should be False in production. Use environment variable to control it.
DEBUG = env_bool("DJANGO_DEBUG", True)

# Hosts allowed to serve the app. Override in production via env variable.
ALLOWED_HOSTS = [host.strip() for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if host.strip()]

JWT_SIGNING_KEY = os.getenv("JWT_SECRET_KEY") or SECRET_KEY

JWT_AUTH = {
    # IMPORTANT: Use a long random secret in production, loaded from env
    "SIGNING_KEY": JWT_SIGNING_KEY,
    "ALGORITHM": "HS256",
 
    # Token lifetimes
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),   # Short-lived: 15 min
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),       # Long-lived: 7 days
 
    # Cookie names
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_REFRESH": "refresh_token",
 
    # Cookie security flags
    "AUTH_COOKIE_HTTPONLY": True,   # JS cannot read the cookie
    "AUTH_COOKIE_SECURE": not DEBUG,  # HTTPS only in prod
    "AUTH_COOKIE_SAMESITE": "Lax", # Protects against CSRF
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders', 
    'rest_framework',
    'drf_yasg',
    'accounts',
    'ingestion',
    'nlp_engine',
    'coding',
    'reports'
]

CORS_ALLOW_ALL_ORIGINS = True 

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",   # React dev server
    "http://localhost:5173",   # Vite dev server
    # "https://yourfrontend.com",
]
 
# CRITICAL: This allows cookies to be sent cross-origin.
# Without this, the browser will strip the cookie from cross-origin requests.
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VirtualMedicalCoder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VirtualMedicalCoder.wsgi.application'

AUTH_USER_MODEL = "accounts.User"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("POSTGRES_DB", "virtualmedicalcoder"),
        "USER": os.getenv("POSTGRES_USER", "medical_user"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "medical_user"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# Celery Configuration
# In production, use a proper Redis instance.
# For local development without Redis, set CELERY_ALWAYS_EAGER=True to run tasks synchronously.
_CELERY_BROKER = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
_CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", _CELERY_BROKER)
if not DEBUG and _CELERY_BROKER.startswith("redis://"):
    # Production: use Redis as configured
    CELERY_BROKER_URL = _CELERY_BROKER
    CELERY_RESULT_BACKEND = _CELERY_RESULT_BACKEND
else:
    # Development: fall back to memory broker if Redis is unavailable
    # To test async locally, start Redis or set CELERY_ALWAYS_EAGER=True
    CELERY_BROKER_URL = _CELERY_BROKER
    CELERY_RESULT_BACKEND = _CELERY_RESULT_BACKEND

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# For testing without Redis, set this to True to run tasks synchronously:
# CELERY_ALWAYS_EAGER = True

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Email / Delivery placeholders (for insurer handoff) ---
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.example.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@example.com")


# --- Basic logging configuration ---
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
}
