# Generated by Django 5.2.12 on 2026-03-08 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soap_note', models.JSONField(default=dict)),
                ('icd_codes', models.JSONField(default=list)),
                ('cpt_codes', models.JSONField(default=list)),
                ('snomed_codes', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw_llm_output', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revised', 'Revised')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_result', to='ingestion.uploadrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
