# Generated by Django 5.2.8 on 2026-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_enhanced_coding_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='extracted_diagnoses',
            field=models.JSONField(default=list, help_text='Diagnoses with source tracking and coding decisions (ICD-10-CM Section I.B.1)'),
        ),
        migrations.AddField(
            model_name='codingresult',
            name='validation_log',
            field=models.JSONField(default=dict, help_text='Source validation gate decisions and reasoning per diagnosis'),
        ),
        migrations.AlterField(
            model_name='reviewfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('missing_code', 'Missing Code Added'), ('incorrect_code', 'Code Corrected'), ('specificity', 'Increased Specificity'), ('completeness', 'Enhanced Completeness'), ('conflict_resolved', 'Conflicting Code Removed'), ('source_misidentified', 'Source Misidentified - Not Physician Confirmed'), ('unverified_condition_coded', 'Unverified Condition Coded - Patient Statement Only'), ('historical_incorrectly_coded', 'Historical Condition Coded as Current'), ('physician_confirmed_not_coded', 'Physician Confirmed But Not Coded'), ('patient_reported_coded', 'Patient-Only Statement Coded - ICD-10-CM Violation'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
