# Generated by Django 5.2.8 on 2026-07-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_codingresult_extracted_diagnoses_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Denormalized from upload_record.organization at creation time, for fast org-scoped queries and permission checks without an extra join.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_results', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='codingresult',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Mirrors upload_record.user -- null for API-only submissions with no individual account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
