# Generated by Django 5.2.8 on 2026-07-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_codingresult_organization_alter_codingresult_user'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresult',
            name='reviewed_by_api_key',
            field=models.ForeignKey(blank=True, help_text='Set instead of reviewed_by when a partner reviews their own result directly via API key.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='organizations.organizationapikey'),
        ),
    ]
