#!/usr/bin/env python
"""
Diagnostic script to debug Stage 2 code generation.
Shows:
1. What clean SOAP is generated by Stage 1
2. What codes Stage 2 is trying to generate
3. Where the mismatch happens
"""

import os
import sys
import json
from pathlib import Path

# Add project to path
sys.path.insert(0, str(Path(__file__).parent / "VirtualMedicalCoder"))

# Set up Django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "VirtualMedicalCoder.settings")
import django
django.setup()

from nlp_engine.two_stage_pipeline import TwoStagePipeline
from coding.evidence_extractor import EvidenceExtractor
from coding.code_retrieval import CodeRetriever


def diagnose_pipeline():
    """Run diagnostic on the trauma case to see where Stage 2 fails"""
    
    raw_text = """
    Doctor: Good afternoon. I can see you've had several accidents. Can you tell 
    me about the most recent one?
    Patient: Yes, doctor. The latest accident happened on October 5, 2025. I was 
    riding my motorcycle when a car suddenly pulled out and hit me.
    Doctor: What kind of injuries did you sustain?
    Patient: My left leg took most of the impact — it's swollen and painful. 
    I also have deep cuts on my right arm.
    Doctor: Alright, let me examine your leg... I can see significant swelling here. 
    Let me check your arm as well. Yes, there are several deep lacerations. 
    We'll need to get X-rays of both areas to rule out fractures.
    """
    
    print("\n" + "="*80)
    print("DIAGNOSTIC: TWO-STAGE PIPELINE DEBUG")
    print("="*80)
    
    print("\n[STAGE 1] Normalizing messy text to clean SOAP...")
    print("-"*80)
    
    pipeline = TwoStagePipeline()
    
    # Run Stage 1 only
    try:
        clean_soap = pipeline.stage_1_normalize_to_soap(raw_text)
        print("✓ Stage 1 succeeded\n")
        print("Clean SOAP generated:")
        print(json.dumps(clean_soap, indent=2))
    except Exception as e:
        print(f"✗ Stage 1 failed: {e}")
        return
    
    # Extract evidence from the clean SOAP
    print("\n" + "="*80)
    print("[EVIDENCE EXTRACTION] Parsing clean SOAP for structured facts...")
    print("-"*80)
    
    try:
        evidence = EvidenceExtractor.extract_evidence(clean_soap)
        print("✓ Evidence extraction succeeded\n")
        print("Extracted diagnoses:")
        for diag in evidence.get("diagnoses", []):
            print(f"  - {diag['condition']} (laterality: {diag.get('laterality', 'N/A')})")
        
        print("\nExtracted procedures:")
        for proc in evidence.get("procedures", []):
            print(f"  - {proc['name']} (approach: {proc.get('approach', 'N/A')})")
        
        print("\nExtracted symptoms:")
        for symptom in evidence.get("symptoms", []):
            print(f"  - {symptom}")
    except Exception as e:
        print(f"✗ Evidence extraction failed: {e}")
        import traceback
        traceback.print_exc()
        evidence = {}
    
    # Run Stage 2
    print("\n" + "="*80)
    print("[STAGE 2] Generating codes from clean SOAP...")
    print("-"*80)
    
    try:
        raw_codes = pipeline.stage_2_generate_codes(clean_soap)
        print(f"✓ Stage 2 succeeded - Generated {len(raw_codes)} codes\n")
        
        print("Raw codes from Stage 2 (before validation):")
        for i, code in enumerate(raw_codes, 1):
            print(f"\n{i}. {code['system']}: {code['code']}")
            print(f"   Description: {code['description']}")
            print(f"   Confidence: {code['confidence']}")
            print(f"   Evidence: {code['evidence_text'][:80]}...")
    except Exception as e:
        print(f"✗ Stage 2 failed: {e}")
        import traceback
        traceback.print_exc()
        return
    
    # Validate codes against database
    print("\n" + "="*80)
    print("[CODE VALIDATION] Checking codes against CSV databases...")
    print("-"*80)
    
    from coding.validation import validator
    
    for code in raw_codes:
        system = code['system']
        code_value = code['code']
        
        is_valid, reason, db_desc = validator.validate_code(system, code_value)
        
        if is_valid:
            print(f"✓ {system} {code_value}: VALID")
            print(f"  DB Description: {db_desc}")
        else:
            print(f"✗ {system} {code_value}: INVALID")
            print(f"  Reason: {reason}")
            print(f"  DB Description: {db_desc}")
    
    # Evidence matching
    print("\n" + "="*80)
    print("[EVIDENCE MATCHING] Checking evidence-code alignment...")
    print("-"*80)
    
    for code in raw_codes:
        evidence_text = code['evidence_text']
        code_value = code['code']
        confidence = code['confidence']
        
        print(f"{code['system']} {code_value}: Confidence {confidence}")
        print(f"  Evidence: {evidence_text[:70]}...")
        
        # Check if evidence matches the code's description
        desc_lower = code['description'].lower()
        evidence_lower = evidence_text.lower()
        
        # Check for key mismatches
        if 'thigh' in desc_lower and 'thigh' not in evidence_lower and 'leg' in evidence_lower:
            print(f"  ⚠️  CODE-EVIDENCE MISMATCH: Description says THIGH but evidence says LEG")
        if 'arm' in desc_lower and 'arm' not in evidence_lower and 'leg' in evidence_lower:
            print(f"  ⚠️  CODE-EVIDENCE MISMATCH: Description says ARM but evidence says LEG")
        if 'knee' in desc_lower and 'knee' not in evidence_lower and 'arm' in evidence_lower:
            print(f"  ⚠️  CODE-EVIDENCE MISMATCH: Description says KNEE but evidence says ARM")
        if 'right' in desc_lower and 'left' in evidence_lower:
            print(f"  ⚠️  LATERALITY MISMATCH: Code says RIGHT but evidence says LEFT")
        if 'left' in desc_lower and 'right' in evidence_lower:
            print(f"  ⚠️  LATERALITY MISMATCH: Code says LEFT but evidence says RIGHT")
        print()


if __name__ == "__main__":
    diagnose_pipeline()
