# Generated by Django 5.2.8 on 2026-07-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_internal_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_review_partner_submissions',
            field=models.BooleanField(default=False, help_text='If true, this user can see and review ASSISTED-mode results submitted by partner organizations, not just their own uploads.'),
        ),
    ]
