# Generated by Django 5.2.8 on 2026-07-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_create_uploadrecord_table'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Which organization this document belongs to. Set from user.organization for browser uploads, or from the API key's organization for machine submissions.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='review_mode_override',
            field=models.CharField(blank=True, help_text="Optional per-upload override of the organization's default review_mode (values match organizations.models.ReviewMode). Empty means 'use the org default'.", max_length=10),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='submitted_by_employee',
            field=models.CharField(blank=True, help_text="Free-text identifier for the person who submitted this document when no full user account exists for them (typical for API-key submissions from a partner's staff).", max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null when submitted purely via an organization API key with no individual user account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
