# Generated by Django 5.2.8 on 2026-07-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('review_mode', models.CharField(choices=[('assisted', 'Assisted (internal coder reviews)'), ('direct', 'Direct (partner reviews their own results)')], default='assisted', help_text='Default review mode for uploads submitted by this organization.', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Human-readable label, e.g. 'Acme Claims System - prod'.", max_length=255)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('key_prefix', models.CharField(editable=False, help_text='First few characters of the raw key, safe to display for identification.', max_length=16)),
                ('scopes', models.JSONField(default=list, help_text='List of APIKeyScope values this key is allowed to use.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
